# Generated by Django 6.0.3 on 2026-03-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_category_description_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
