# Generated by Django 6.0.3 on 2026-03-13 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='studioclass',
            options={'verbose_name_plural': 'Studio Classes'},
        ),
        migrations.AlterField(
            model_name='studioclass',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studioclasses', to='classes.category'),
        ),
        migrations.AlterField(
            model_name='studioclass',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='studioclass',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studioclass',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='classes/'),
        ),
    ]
