# Generated by Django 6.0.3 on 2026-03-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_category_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studioclass',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
