# Generated by Django 6.0.3 on 2026-04-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_studioclass_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='studioclass',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
