# Generated by Django 6.0.3 on 2026-07-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_booked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='additional_notes',
            field=models.TextField(blank=True, help_text='accessibility requirements, dietary needs, equipment preferences', null=True),
        ),
    ]
